### ISSUE TITLE
What sensors do you want, and things to buy

### ISSUE THREAD

**Issue by TechplexEngineer** [FRCteam4909/2019-Deep-Space#10]
Given the white tape alignment lines on the carpet, the reflective tape on the Rocket etc. what sensors do you want on the robot?

We have many choices:
- Ultrasonic
- Lidar
- Color
- Pixy / Vision Processing
...

**Comment by roshanr10** [comment]
I think overall those are only two non-drivetrain semiautonomous features that we're aiming to hit, I think it would be good to do both tbh, the line for catching it while driving by, I think that's easier to align within a binary style line follower.

As for vision, I think to be able to find the height would be useful. since the offset is the same, we could even have the setpoints for the rocket change dependent on the face; far-fetched but that could still save time during the match.

any thoughts? @TechplexEngineer @derrell @ashwinc12

**Comment by derrell** [comment]
The line following, on the ground is likely to be the easier of the two to get going with. I'd recommend getting it working first. It, however, will not be as accurate as lining up on the reflective tape, so if we get the line-following working, and then other "mandatory" things done, we should then get back to homing in on the reflective tape.

**Comment by roshanr10** [comment]
do we want to keep this issue open? it's very general, and has no inherent value – I'll close this and create new ones based upon our existing discussions
